package model;

// Generated Jul 19, 2014 11:26:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "altp")
public class Question implements java.io.Serializable {

	private Integer questionId;
	private String content;
	private String ansA;
	private String ansB;
	private String ansC;
	private String ansD;
	private String ansKey;
	private int level;

	public Question() {
	}

	public Question(String content, String ansA, String ansB, String ansC,
			String ansD, String ansKey, int level) {
		this.content = content;
		this.ansA = ansA;
		this.ansB = ansB;
		this.ansC = ansC;
		this.ansD = ansD;
		this.ansKey = ansKey;
		this.level = level;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "questionID", unique = true, nullable = false)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "content", nullable = false, length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "ansA", nullable = false, length = 200)
	public String getAnsA() {
		return this.ansA;
	}

	public void setAnsA(String ansA) {
		this.ansA = ansA;
	}

	@Column(name = "ansB", nullable = false, length = 200)
	public String getAnsB() {
		return this.ansB;
	}

	public void setAnsB(String ansB) {
		this.ansB = ansB;
	}

	@Column(name = "ansC", nullable = false, length = 200)
	public String getAnsC() {
		return this.ansC;
	}

	public void setAnsC(String ansC) {
		this.ansC = ansC;
	}

	@Column(name = "ansD", nullable = false, length = 200)
	public String getAnsD() {
		return this.ansD;
	}

	public void setAnsD(String ansD) {
		this.ansD = ansD;
	}

	@Column(name = "ansKey", nullable = false, length = 10)
	public String getAnsKey() {
		return this.ansKey;
	}

	public void setAnsKey(String ansKey) {
		this.ansKey = ansKey;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
