package model;

// Generated Jul 19, 2014 11:26:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Quickquestion generated by hbm2java
 */
@Entity
@Table(name = "quickquestion", catalog = "altp")
public class Quickquestion implements java.io.Serializable {

	private Integer quickId;
	private String content;
	private String ansA;
	private String ansB;
	private String ansC;
	private String ansD;
	private String ansKey;

	public Quickquestion() {
	}

	public Quickquestion(String content, String ansA, String ansB, String ansC,
			String ansD, String ansKey) {
		this.content = content;
		this.ansA = ansA;
		this.ansB = ansB;
		this.ansC = ansC;
		this.ansD = ansD;
		this.ansKey = ansKey;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "quickID", unique = true, nullable = false)
	public Integer getQuickId() {
		return this.quickId;
	}

	public void setQuickId(Integer quickId) {
		this.quickId = quickId;
	}

	@Column(name = "content", nullable = false, length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "ansA", nullable = false, length = 200)
	public String getAnsA() {
		return this.ansA;
	}

	public void setAnsA(String ansA) {
		this.ansA = ansA;
	}

	@Column(name = "ansB", nullable = false, length = 200)
	public String getAnsB() {
		return this.ansB;
	}

	public void setAnsB(String ansB) {
		this.ansB = ansB;
	}

	@Column(name = "ansC", nullable = false, length = 200)
	public String getAnsC() {
		return this.ansC;
	}

	public void setAnsC(String ansC) {
		this.ansC = ansC;
	}

	@Column(name = "ansD", nullable = false, length = 200)
	public String getAnsD() {
		return this.ansD;
	}

	public void setAnsD(String ansD) {
		this.ansD = ansD;
	}

	@Column(name = "ansKey", nullable = false, length = 10)
	public String getAnsKey() {
		return this.ansKey;
	}

	public void setAnsKey(String ansKey) {
		this.ansKey = ansKey;
	}

}
