package model;

// Generated Jul 19, 2014 11:26:44 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Round generated by hbm2java
 */
@Entity
@Table(name = "round", catalog = "altp")
public class Round implements java.io.Serializable {

	private Integer roundId;
	private Player player;
	private int help;
	private String questionlist;
	private int status;

	public Round() {
	}

	public Round(Player player, int help, String questionlist, int status) {
		this.player = player;
		this.help = help;
		this.questionlist = questionlist;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "roundID", unique = true, nullable = false)
	public Integer getRoundId() {
		return this.roundId;
	}

	public void setRoundId(Integer roundId) {
		this.roundId = roundId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mainplayer", nullable = false)
	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	@Column(name = "help", nullable = false)
	public int getHelp() {
		return this.help;
	}

	public void setHelp(int help) {
		this.help = help;
	}

	@Column(name = "questionlist", nullable = false, length = 200)
	public String getQuestionlist() {
		return this.questionlist;
	}

	public void setQuestionlist(String questionlist) {
		this.questionlist = questionlist;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
